name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - name: test
      run: echo "${{ github.repository }}"
    - uses: actions/checkout@v1
    - uses: ./action-a
      env:
        MY_NAME: "Khalid"
