name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - name: Github repo
      run: echo "${{ github.repository }}"
    - name: Github ref
      run: echo "${{ github.ref }}"
    - name: Github base ref
      run: echo "${{ github.base_ref }}"
    - name: Github workspace
      run:  echo "${{ github.workspace }}"
    - uses: actions/checkout@v2
    - uses: ./action-a
      env:
        MY_NAME: "Khalid"
